In [ ]:
#The first project in your PDF is “NumPy Data Explorer”. It requires:

Array creation

Indexing and slicing

Mathematical & statistical operations

Reshaping and broadcasting

Save and load NumPy arrays

Compare NumPy with Python lists

In [1]:
import numpy as np
import time

arr = np.array([10, 20, 30, 40, 50])
print("Original Array:", arr)

print("First element:", arr[0])
print("Last element:", arr[-1])
print("Slice (1:4):", arr[1:4])

print("Array + 5:", arr + 5)
print("Array * 2:", arr * 2)

print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
print("Sum:", np.sum(arr))

arr2 = np.arange(1, 10)
matrix = arr2.reshape(3,3)
print("Reshaped Matrix:\n", matrix)

print("Broadcasting (matrix + 10):\n", matrix + 10)

np.save("data_array.npy", arr)
loaded_array = np.load("data_array.npy")
print("Loaded Array:", loaded_array)

list_data = list(range(1000000))
start = time.time()
result_list = [x + 5 for x in list_data]
end = time.time()
print("Python List Time:", end - start)

numpy_data = np.arange(1000000)
start = time.time()
result_numpy = numpy_data + 5
end = time.time()
print("NumPy Array Time:", end - start)

Original Array: [10 20 30 40 50]
First element: 10
Last element: 50
Slice (1:4): [20 30 40]
Array + 5: [15 25 35 45 55]
Array * 2: [ 20  40  60  80 100]
Mean: 30.0
Median: 30.0
Max: 50
Min: 10
Sum: 150
Reshaped Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Broadcasting (matrix + 10):
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
Loaded Array: [10 20 30 40 50]
Python List Time: 0.07088589668273926
NumPy Array Time: 0.0038869380950927734
